export const workoutTemplates = [
  {
    id: 'upper-a',
    name: 'Upper A',
    focus: 'Heavy press and row',
    estimatedMinutes: 65,
    exercises: [
      { id: 'bench-press', order: 1, name: 'Bench Press', sets: 4, reps: '5', target: 'strength' },
      { id: 'barbell-row', order: 2, name: 'Barbell Row', sets: 4, reps: '6', target: 'strength' },
      { id: 'overhead-press', order: 3, name: 'Overhead Press', sets: 3, reps: '8', target: 'strength' },
      { id: 'face-pulls', order: 4, name: 'Face Pulls', sets: 3, reps: '15', target: 'upper back' },
      { id: 'weighted-dips', order: 5, name: 'Weighted Dips', sets: 3, reps: '8', target: 'push' },
      { id: 'ez-curl', order: 6, name: 'EZ Curl', sets: 3, reps: '10', target: 'arms' },
    ],
  },
  {
    id: 'lower-a',
    name: 'Lower A',
    focus: 'Squat and quad focus',
    estimatedMinutes: 60,
    exercises: [
      { id: 'back-squat', order: 1, name: 'Back Squat', sets: 4, reps: '6', target: 'strength' },
      { id: 'leg-press', order: 2, name: 'Leg Press', sets: 3, reps: '10', target: 'quads' },
      { id: 'walking-lunges', order: 3, name: 'Walking Lunges', sets: 3, reps: '12', target: 'single leg' },
      { id: 'calf-raise-a', order: 4, name: 'Calf Raise', sets: 4, reps: '15', target: 'calves' },
      { id: 'leg-extension', order: 5, name: 'Leg Extension', sets: 3, reps: '12', target: 'quads' },
    ],
  },
  {
    id: 'upper-b',
    name: 'Upper B',
    focus: 'Volume upper body',
    estimatedMinutes: 60,
    exercises: [
      { id: 'incline-db-press', order: 1, name: 'Incline DB Press', sets: 4, reps: '10', target: 'push' },
      { id: 'pull-ups', order: 2, name: 'Pull-Ups', sets: 4, reps: '8', target: 'pull' },
      { id: 'lateral-raise', order: 3, name: 'Lateral Raise', sets: 4, reps: '15', target: 'delts' },
      { id: 'cable-fly', order: 4, name: 'Cable Fly', sets: 3, reps: '12', target: 'chest' },
      { id: 'hammer-curl', order: 5, name: 'Hammer Curl', sets: 3, reps: '12', target: 'arms' },
      { id: 'pushdown', order: 6, name: 'Pushdown', sets: 3, reps: '12', target: 'arms' },
    ],
  },
  {
    id: 'lower-b',
    name: 'Lower B',
    focus: 'Hinge and posterior chain',
    estimatedMinutes: 60,
    exercises: [
      { id: 'deadlift', order: 1, name: 'Deadlift', sets: 4, reps: '5', target: 'strength' },
      { id: 'romanian-deadlift', order: 2, name: 'Romanian Deadlift', sets: 3, reps: '10', target: 'hinge' },
      { id: 'leg-curl', order: 3, name: 'Leg Curl', sets: 3, reps: '12', target: 'hamstrings' },
      { id: 'hip-thrust', order: 4, name: 'Hip Thrust', sets: 3, reps: '10', target: 'glutes' },
      { id: 'calf-raise-b', order: 5, name: 'Calf Raise', sets: 4, reps: '15', target: 'calves' },
    ],
  },
  {
    id: 'full-body',
    name: 'Full Body',
    focus: 'Full body with optional accessories',
    estimatedMinutes: 45,
    exercises: [
      { id: 'squat-variation', order: 1, name: 'Squat Variation', sets: 3, reps: '8', target: 'lower' },
      { id: 'bench-variation', order: 2, name: 'Bench Variation', sets: 3, reps: '8', target: 'push' },
      { id: 'row-variation', order: 3, name: 'Row Variation', sets: 3, reps: '8', target: 'pull' },
    ],
  },
];
